version: "3.9"
services:
  postgres:
    container_name: "bot_db"
    image: postgres:15.1
    environment:
      POSTGRES_DB: "docdb"
      POSTGRES_USER: "vymanvar"
      POSTGRES_PASSWORD: "1234"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
  server:
    container_name: "tg_bot"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
